version: '3.9'

services:
  renting-api:
    build:
      context: .
      dockerfile: src/Renting.WebApi/Dockerfile
    ports:
      - "5000:5000"

  tests:
    build:
      context: .
      dockerfile: tests/Dockerfile
